# Generated by Django 3.2 on 2021-04-25 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date of performance')),
                ('streamyard_link', models.URLField()),
                ('youtube_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performer', models.CharField(max_length=200)),
                ('parent_email', models.EmailField(max_length=254)),
                ('performer_email', models.EmailField(max_length=254)),
                ('instrument', models.CharField(max_length=50)),
                ('piece', models.CharField(max_length=200)),
                ('composer', models.CharField(max_length=200)),
                ('piece_length', models.DurationField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signups.event')),
            ],
        ),
    ]
