# Generated by Django 3.2 on 2021-04-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0003_alter_signup_performer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='performer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
