# Generated by Django 3.2 on 2021-04-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0005_alter_signup_performer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='signup_limit',
            field=models.IntegerField(default=8),
        ),
    ]
