# Generated by Django 3.2 on 2021-04-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0006_event_signup_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='signup_limit',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
