# Generated by Django 3.2 on 2021-04-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0007_alter_event_signup_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='Tacy Foundation Virtual Live Performance', max_length=200),
        ),
    ]
