# Generated by Django 3.2 on 2021-05-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0008_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='order_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signup',
            name='order_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
